### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by colinluthier** [philrandal/gpsctl#12]
I was trying to build for a pi4 from you blog and when I got to:

$ .build.sh

The output is:
gcc: error: unrecognized command line option ‘-mapcs’; did you mean ‘--specs’?
gcc: error: unrecognized command line option ‘-mno-sched-prolog’; did you mean ‘-Wno-sign-promo’?

gpsctl is not built after these errors.

**Comment by philrandal** [comment]
Works for me on the latest Raspberry Pi OS Lite build.

`gcc  --version` gives

`gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
`

**Comment by colinluthier** [comment]
I tried the 64 bit buster and the 32 bit buster lite with the same error. I tried gcc 8 and 10. I'll dig back into it and see what I have messed up.

**Comment by colinluthier** [comment]
I finally got it to build. For some reason it was not correctly building the files in the vendor folder and leaving them blank. I had to try a couple of times to build with a -recursive flag and then everything worked. I am not exactly sure what I was doing wrong or finally did right.
