### ISSUE TITLE
Feature request: add option to force a cold start

### ISSUE THREAD

**Issue by jasonbphillips** [philrandal/gpsctl#13]
Currently, the --reset option requests a hot start of the GPS. I'd like to request a new option (perhaps --coldreset) that requests a cold start of the GPS.

My use case is that when testing various configurations I'd like to be sure that the GPS is starting from a clean state and reaquires the information it needs to work with the settings previously saved to RAM using the --save_config option. I was tipped off in the ublox protocol specification where it recommends a cold start after changing constellation settings (see section 4.2.1 Switching between GNSS):

https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf

This conversation has relevant info:

https://github.com/PX4/PX4-GPSDrivers/issues/26

Thanks for considering this, Phil.

Jason

**Comment by philrandal** [comment]
Due to circumstances beyond my control, I'm not able to work on this.

It should be easy enough to add. 

Patches welcome.

**Comment by philrandal** [comment]
Changed the --reset semantics to perform a cold start instead of a hot start.

Fixed in https://github.com/philrandal/gpsctl/releases/tag/v1.15

**Comment by jasonbphillips** [comment]
Thank you, Phil.

Jason
