### ISSUE TITLE
Can't compile on debian bullseye

### ISSUE THREAD

**Issue by mkmt** [philrandal/gpsctl#14]
Problem:
/usr/bin/ld: /tmp/ccZyN4SF.o: in function `actionTestPPS':
gpsctl.c:(.text+0x3000): undefined reference to `wiringPiSetup'
/usr/bin/ld: gpsctl.c:(.text+0x300c): undefined reference to `pinMode'
/usr/bin/ld: gpsctl.c:(.text+0x3058): undefined reference to `digitalRead'
collect2: error: ld returned 1 exit status

WiringPi installed.
Debian version 11, raspbian.

**Comment by philrandal** [comment]
Unfortunately, I am not able to look at this at the moment. 

I think it is caused by the the use of a newer gcc in Bullseye.

It's probably time to migrate to another C GPIO library.

**Comment by philrandal** [comment]
Removed wiringPi-dependent code

https://github.com/philrandal/gpsctl/releases/tag/v1.14
