### ISSUE TITLE
Could not synchronize on any baud rate...

### ISSUE THREAD

**Issue by brandonros** [philrandal/gpsctl#17]
```
gpsctl -a -B 115200 --configure_for_timing -vv
Serial port ("/dev/tty.usbmodem11101") open...
Serial port open and configured...
Automatically determining baud rate...
Trying 230400 baud...
Trying 115200 baud...
Trying 57600 baud...
Trying 38400 baud...
Trying 19200 baud...
Trying 9600 baud...
Could not synchronize on any baud rate...
Changing baud rate to 115200...
Error: timed out while waiting to receive UBX message
   Caused: Problem receiving poll response
   Caused: Problem polling for current configuration before changing baud rate
   Caused: failed to change baud rate
   Caused: command line options processing error during action phase: fatal error.
 ```

![image](https://user-images.githubusercontent.com/8949910/129615005-e909fd87-2ec2-45c1-b18c-d69a25f3abcf.png)

https://www.amazon.com/gp/product/B07ZR8R17Q/

**Comment by philrandal** [comment]
This usually means that something else has its mitts on the serial device, preventing gpsctl from syncing.

As my modifications to the upstream code consist mainly of config file handling, I am not sure how you can resolve the issue.

I've never tried this code against a USB interface.  It's not designed for that purpose and I have no idea what modifications to the code would be necessary to support USB devices, if any.

**Comment by brandonros** [comment]
I plugged the same device into a Windows laptop (above was from Mac OS X) and it semi-worked with the u-blox software. I will update when I get the antenna that goes with it.

**Comment by philrandal** [comment]
.

**Comment by philrandal** [comment]
The program was written for Raspberry Pis with the Uputronics GPS HAT. I've tested on Raspberry Pi OS Jessie,  Buster,  and Bullseye. Any other platform and you're on your own. Your symptoms suggest that another program is trying to access the GPS module at the same time as gpsctl

**Comment by brandonros** [comment]
Ok. I appreciate the help. Last thing, do you think it would be an easy fix to be able to work with `gpsctl` given the fact that screen actually works?

```
Brandons-MacBook-Air:gpsctl brandonros 2021-08-18 19:04:57 $ screen /dev/tty.usbmodem11401 9600 
$GNTXT,01,01,02,u-blox AG - www.u-blox.com*4E
$GNTXT,01,01,02,HW UBX-M8030 00080000*60
$GNTXT,01,01,02,ROM CORE 3.01 (107888)*2B
$GNTXT,01,01,02,FWVER=SPG 3.01*46
$GNTXT,01,01,02,PROTVER=18.00*11
$GNTXT,01,01,02,GPS;GLO;GAL;BDS*77
$GNTXT,01,01,02,SBAS;IMES;QZSS*49
$GNTXT,01,01,02,GNSS OTP=GPS;GLO*37
$GNTXT,01,01,02,LLC=FFFFFFFF-FFFFFFFF-FFFFFFFF-FFFFFFFF-FFFFFFFD*2F
$GNTXT,01,01,02,ANTSUPERV=AC SD PDoS SR*3E
$GNTXT,01,01,02,ANTSTATUS=OK*25
$GNTXT,01,01,02,PF=3FF*4B
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
```

**Comment by brandonros** [comment]
Bunch of other programs are able to get a handle on the device no problem. Ended up using https://www.npmjs.com/package/gps

Thanks for your help. Let me know if you want to debug the serial portion of this not reading correctly on Mac. Could be a cool expansion.

**Comment by philrandal** [comment]
One more thing you can try.

Test the version in Tom Dilatush's slightlyloony repo I forked gpsctl from.

You'll need to hard code the serial port as --port is not correctly handled
in his code.

You'll also notice a comment in my fork that the timing code doesn't seem
correct.

I did mess with that a bit when I was having intermittent similar problems
to yours.

Good luck.

Phil
