### ISSUE TITLE
The specified baud rate ("460800") is not a valid one

### ISSUE THREAD

**Issue by MaffooClock** [philrandal/gpsctl#18]
I have my MAX-M8Q set to use a baud rate of 460800, and it works fine.  And just to confirm, it is also listed as a valid option in [UBX-13003221](https://content.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf) (page 36).

I would like to suggest that you add `{ 460800, B460800 }` to `validRates[]` 

https://github.com/philrandal/gpsctl/blob/d50e6b25c9c94edb261774a117bb02831c2f173e/sl_serial.c#L125-L144

I may submit a PR a little later if that's welcome.

**Comment by philrandal** [comment]
Thanks for the report.

Fixed in release v1.17
